---
title: "AR99 underway maps"
author: "Brett Longworth"
date: "2026-01-17"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# libraries
library(tidyverse)
library(eimsr)
library(here)
library(dygraphs)
library(plotly)

theme_set(theme_classic())
```


```{r}
source(here("inst/get_AR99_data.R"))

cruise_start <- as.POSIXct("2026-01-13 17:30:00", tz = "UTC")

eims <- eims |>
  filter(timestamp > cruise_start) |>
  mutate(mass_3240 = mass_32 / mass_40)

optode <- filter(optode, timestamp > cruise_start)
temps <- filter(temps, timestamp > cruise_start)
underway <- filter(underway, timestamp > cruise_start)
```

# Plots!

## EIMS

40/32 over time. Check that data are continuous and no major noise or ratio issues. 

```{r}
plot_eims_air_bands(eims, "mass_3240", yaxis_title = "Mass 32/40")
```

## Optode

Air saturation over time. Ugh. 

```{r}
plot_ts(optode, "air_saturation")
```



## temp server

### Thermistor

```{r}
plot_ts(temps, "thermistor")
```

```{r}
plot_ts(temps, "water_flow")
```

```{r}
plot_ts(temps, "pressure")
```

## Underway

```{r}
plot_ts(underway, "FLOW")
```


```{r}
ggplot(underway, aes(timestamp, FLOW)) +
  geom_line(size = .2) +
  ggtitle("Underway Seawater Flow")
```

```{r}
plot_ts(underway, "SBE48T")
```

```{r}
plot_ts(underway, "SBE45S")
```

```{r}
plot_ts(underway, "FLR")
```

## Figures for cruise report

Oxygen saturation

```{r}
ggplot(optode, aes(timestamp, air_saturation)) +
  geom_line(size = 0.4) +
  labs(title = "EIMS Optode Air Saturation",
       x = NULL,
       y = "Air Saturation (%)")
```

Annotated EIMS 32/40 during DMS system tests on January 14, 2026.

```{r}

events <- tibble(
  timestamp  = as.POSIXct(c("2026-01-14 15:28:00",
                            "2026-01-14 15:41:00",
                            "2026-01-14 18:42:00",
                            "2026-01-14 19:26:00",
                            "2026-01-14 20:23:00"),
                          tz = "UTC"),
  label = c("DMS ozone off",
            "DMS compressor off",
            "DMS compressor on",
            "DMS w/air compressor",
            "DMS on, outlets taped and in hood")
)

eims |> 
  filter(timestamp > as.POSIXct("2026-01-14 12:00:00", tz = "UTC"),
         timestamp < as.POSIXct("2026-01-15 00:00:00", tz = "UTC")) |>
  plot_eims_air_bands("mass_3240", yaxis_title = "Mass 32/40", ggplot = TRUE) +
  geom_vline(
    data = events,
    aes(xintercept = timestamp),  # for Date/POSIXct use numeric
    linetype = "dashed",
    color = "blue",
    alpha = 0.7
  ) +
  # optional: labels at top of panel
  geom_text(
    data = events,
    aes(x = timestamp, y = Inf, label = label),
    angle = 90,           # rotate text vertically
    vjust = -0.2,         # nudge a bit inside from the axis
    hjust = 1.1, 
    color = "blue",
    size = 3
  ) +
  labs(
    title = "EIMS Mass 32/40 During DMS System Tests",
    x = NULL
  )
```
